/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          blue: "#0066ff",
          "blue-dark": "#0052cc",
          "blue-light": "#3388ff",
        },
        bg: {
          primary: "#ffffff",
          secondary: "#f8fafc",
          dark: "#000000",
        },
        text: {
          primary: "#1a202c",
          secondary: "#718096",
        },
        border: {
          color: "#e2e8f0",
        },
      },
      fontFamily: {
        sans: ["Inter", "Poppins", "sans-serif"],
        code: ["Fira Code", "source-code-pro", "monospace"],
      },
      animation: {
        "slide-in-right": "slideInRight 0.3s ease-out",
        "slide-out-right": "slideOutRight 0.3s ease-in",
        "fade-in-up": "fadeInUp 0.5s ease-out",
        "fade-in": "fadeIn 0.6s ease-out",
        "pulse-blue": "pulse-blue 2s infinite",
        glow: "glow 2s ease-in-out infinite",
        "header-wave": "headerWave 3s ease-in-out infinite",
        "text-glow": "textGlow 2s ease-in-out infinite",
        "particle-move": "particleMove 2s ease-out infinite",
        shimmer: "shimmer 2s infinite",
        dash: "dash 2s linear infinite",
        float: "float 3s ease-in-out infinite",
        "bounce-delayed": "bounce-delayed 2s infinite",
      },
      keyframes: {
        slideInRight: {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        slideOutRight: {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(100%)", opacity: "0" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-blue": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        glow: {
          "0%, 100%": { boxShadow: "0 0 5px var(--primary-blue)" },
          "50%": { boxShadow: "0 0 20px var(--primary-blue)" },
        },
        headerWave: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-2px)" },
        },
        textGlow: {
          "0%, 100%": { textShadow: "0 0 5px rgba(59, 130, 246, 0.5)" },
          "50%": { textShadow: "0 0 20px rgba(59, 130, 246, 0.8), 0 0 30px rgba(59, 130, 246, 0.6)" },
        },
        particleMove: {
          "0%": { transform: "translateY(0px) rotate(0deg)", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { transform: "translateY(-20px) rotate(360deg)", opacity: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
        dash: {
          "0%": { strokeDashoffset: "0" },
          "100%": { strokeDashoffset: "24" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "bounce-delayed": {
          "0%, 20%, 50%, 80%, 100%": { transform: "translateY(0)" },
          "40%": { transform: "translateY(-10px)" },
          "60%": { transform: "translateY(-5px)" },
        },
      },
    },
  },
  plugins: [],
  corePlugins: {
    // 사용하지 않는 기능 비활성화
    preflight: false,
    container: false,
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundImage: false,
    backgroundOpacity: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    divideWidth: false,
    fill: false,
    gradientColorStops: false,
    listStyleImage: false,
    listStylePosition: false,
    listStyleType: false,
    objectFit: false,
    objectPosition: false,
    outline: false,
    outlineColor: false,
    outlineOffset: false,
    outlineOpacity: false,
    outlineStyle: false,
    outlineWidth: false,
    placeholderColor: false,
    placeholderOpacity: false,
    ringColor: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    ringWidth: false,
    scale: false,
    skew: false,
    stroke: false,
    strokeWidth: false,
    textDecorationColor: false,
    textDecorationLine: false,
    textDecorationStyle: false,
    textDecorationThickness: false,
    textUnderlineOffset: false,
    textIndent: false,
    verticalAlign: false,
    whitespace: false,
    wordBreak: false,
    backgroundOrigin: false,
    borderImageOutset: false,
    borderImageRepeat: false,
    borderImageSlice: false,
    borderImageSource: false,
    borderImageWidth: false,
  },
};
