export const propsData = [
  {
    name: "data",
    type: "object",
    required: true,
    default: "{ nodes: [], links: [] }",
    description: "노드와 링크 데이터",
  },
  {
    name: "width",
    type: "number",
    required: false,
    default: "800",
    description: "다이어그램 너비",
  },
  {
    name: "height",
    type: "number",
    required: false,
    default: "400",
    description: "다이어그램 높이",
  },
  {
    name: "selectedFlow",
    type: "string",
    required: false,
    default: "null",
    description: "선택된 흐름 ID",
  },
  {
    name: "onFlowSelect",
    type: "function",
    required: false,
    default: "null",
    description: "흐름 선택 콜백",
  },
  {
    name: "nodeWidth",
    type: "number",
    required: false,
    default: "20",
    description: "노드 너비",
  },
  {
    name: "linkOpacity",
    type: "number",
    required: false,
    default: "0.6",
    description: "링크 투명도",
  },
  {
    name: "showTooltip",
    type: "boolean",
    required: false,
    default: "true",
    description: "툴팁 표시 여부",
  },
  {
    name: "showValues",
    type: "boolean",
    required: false,
    default: "true",
    description: "노드 라벨 표시 여부",
  },
  {
    name: "nodeClassName",
    type: "string",
    required: false,
    default: '""',
    description: "모든 노드에 적용할 TailwindCSS 클래스",
  },
  {
    name: "linkClassName",
    type: "string",
    required: false,
    default: '""',
    description: "모든 링크에 적용할 TailwindCSS 클래스",
  },
  {
    name: "svgClassName",
    type: "string",
    required: false,
    default: "border border-gray-200 rounded-lg bg-white shadow-sm",
    description: "SVG 요소에 적용할 TailwindCSS 클래스",
  },
  {
    name: "tooltipClassName",
    type: "string",
    required: false,
    default: "absolute z-10 bg-gray-800 text-white text-sm px-3 py-2 rounded-lg shadow-lg pointer-events-none",
    description: "툴팁에 적용할 TailwindCSS 클래스",
  },
  {
    name: "labelClassName",
    type: "string",
    required: false,
    default: "font-medium select-none transition-all duration-300",
    description: "라벨에 적용할 TailwindCSS 클래스",
  },
  {
    name: "customNodeStyles",
    type: "object",
    required: false,
    default: "{}",
    description: "모든 노드에 적용할 커스텀 스타일",
  },
  {
    name: "customLinkStyles",
    type: "object",
    required: false,
    default: "{}",
    description: "모든 링크에 적용할 커스텀 스타일",
  },
];
